import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./authProvider";
import {Navbar} from "./navbar";
import '@rainbow-me/rainbowkit/styles.css';
import React from 'react';
import ReactDOM from 'react-dom';

const inter = Inter({ subsets: ["latin"] });
/*
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
*/
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>

          <AuthProvider>
            <Navbar />
            {children}
          </AuthProvider>


      </body>
    </html>
  );
}
